### ISSUE TITLE
BMS reported SOC always at 0%

### ISSUE THREAD

**Issue by FAB1150** [lolwheel/Owie#29]
As the title says, the "BMS reported SOC" is always at 0% in the Owie web interface. I have plugged the board in, rebooted it, and ridden it for a bit, but it stays at 0%.

I have verified that my wiring is correct, and the Owie does report the charge to the main board (aka "overridden SOC" is correctly displayed  both in the web interface and the OW app).
The board is an XR and the battery is the stock XR battery, I have just added the Owie for the data it gives me.

As I cannot read what's in the "monitor BMS data" page to tell if it's a problem with the BMS or with the Owie, I'll attach it under here.

Main page in the interface:
![Screenshot_20220409-024224](https://user-images.githubusercontent.com/23463665/162549920-8017520e-4f1e-4197-bed6-62381089091e.jpg)

Monitor BMS data page:
![Screenshot_20220409-024255](https://user-images.githubusercontent.com/23463665/162549950-64998844-3dff-44e2-be0f-fdf70b3b905c.jpg)

**Comment by FAB1150** [comment]
I forgot to mention that the battery is the stock XR battery, in an XR.

**Comment by mretich** [comment]
Hi, have you charged your Board in the meantime?
Because my guess is, that it has probably something to do that BMS goes through a state reset and doesn't know the status of the battery, and plugging the board into a charger corrects this issue by forcing the BMS (and controller potentially) to do a state check.
(Like the problem with the 1% Battery reporting)

**Comment by FAB1150** [comment]
That was my first thought too at first, but I have put it into charge a few times, and it still reports 0%. I have also done a few miles on it now. 
I have not charged it to a full 100% or discharged it to actual 0% yet though, should I try to do it?

**Comment by lolwheel** [comment]
Try charging the board fully. Your board would have shown 0% even if you completely removed Owie. This is the BMS itself acting up.

One of the users has seen a behavior like this. He said it was fixed by fully charging. See https://github.com/lolwheel/Owie#board-reporting-battery-at-1-after-install

**Comment by FAB1150** [comment]
Sorry for the delay, but charging to 100% did fix it. I don't know why charging it to 70-80% didn't do anything before, but it now works flawlessly. Thanks!
