### ISSUE TITLE
4206 BMS won't power D1 Mini Lite once TX is connected

### ISSUE THREAD

**Issue by thibauddavid** [lolwheel/Owie#30]
Hi,

Following up the discussion we had a while ago on Discord, I got time to dig a bit more into the issue I have.

When installing Owie on a 4206 BMS, the D1 Mini lite won't power up (no light at all on it), if motherboard-white is connected to TX.

If I desolder this wire, D1 powers up without issue. 

A little video demonstrating the problem:

https://user-images.githubusercontent.com/6173704/163044161-f7f1fa7c-f693-4aa2-8551-f27b0c4e752b.mov

I've tried multiple combination, and the only explanation I came to is that 4206 don't start delivering current through PROG1 until some condition is met.
My theory is that there could be a (now legacy) header sent, that owie somehow absorbs, preventing the BMS to fully power on. 
Another thing that makes me confirm this, is that if I use an external power source to power on my D1 when fully connected to bms+motherboard, D1 successfully powers up, but there isn't any data showing up on BMS monitoring.
I tripled check all connections several times, and even tried with another D1 Mini Lite, so I'm 200% sure it's not a connection/hardware issue.

Here is my BMS data as soon as I boot my XR, with TX disconnected + D1 powered externally (to be able to capture earliest bits). There might be something odd in there which only happens on 4206 (as I think this is currently the only BMS Owie wasn't successfully installed on)

https://user-images.githubusercontent.com/6173704/163041814-be557ba9-eb0b-4eda-af08-ba22fc3965e8.mov

Not sure what other information I could provide to help debugging this.

**Comment by lolwheel** [comment]
Hmmm this is pretty odd indeed. Can you observe the voltage powering the Owie when you play with that wire?

I remember that when I traced the power pins on the BMS that I use for power pickup, they lead directly to the ground and the onboard power supply inductor output. The BMS controller doesn't have any say in whether or not the power is delivered to those pins, it's either all of the BMS is on or everything is off.

When powering Owie board externally, you need to have common ground between the external power and the BMS ground. Otherwise the board won't be able to read any data.

To address some other concerns - Owie forwards all packets it doesn't understand. Also, the communication is unidirectional - the BMS doesn't know or care if there's anything connected to the other side, it'll keep sending packets anyways.

My hunch is that you're picking up the 5 volts from something that's not exactly power output on the BMS. First - look at the Owie power supply voltages, Second - trace the 5v and Gnd connectors you're using.

Please reach out to me on Discord, the issue tracker isn't place for 1:1 debugging sessions.
