### ISSUE TITLE
d1 mini recommendation in the readme has no stock

### ISSUE THREAD

**Issue by straef** [lolwheel/Owie#34]
the amazon link you include in the readme is for a product that has no stock and may not get any more. also they seem to be a ripoff of the actual d1 mini. looking for alternatives i found several products with reviews pointing out issues where lower quality parts were used instead of the spec of the official wemos (now lolin) d1 mini series.

https://www.wemos.cc/en/latest/d1/d1_mini.html has links to their official aliexpress store.

not sure if this is official being resold or a ripoff but i found this which has stock and if not official seems to be the best counterfeit.
https://www.amazon.com/Development-MicroPython-Nodemcu-Arduino-Compatible/dp/B07H22CDQ8

**Comment by mretich** [comment]
@straef:
Ordering from amazon.de (since I'm from Europe (Austria)) is still possible for this product:
https://www.amazon.de/gp/product/B08BTRPMV1/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1
(This is NOT the original WEMOS/LOLIN board! But works like a charm. I have already installed 3 of these boards)

**Comment by lolwheel** [comment]
Any crappy clone will do.
