### ISSUE TITLE
XR isn't charging fully after OWIE install 

### ISSUE THREAD

**Issue by briderx** [lolwheel/Owie#64]
When I charge my XR (stock battery) after riding, it doesn't seem to charge fully. I have to unplug it and plug it back in for it to charge more. The below pictures show it "fully charged". The first two pics were taken within a minute or two max of each other.
The second two are a few hours charging, after unplugging and plugging it back in. This happens every time. I even swapped chips, thinking there was something wrong with the first one.

Initial Full Charge:
![Screenshot_20221012_152822_CaptivePortalLogin](https://user-images.githubusercontent.com/19560753/195483263-68e4ef8d-c39c-4386-a4e8-9885e811ad65.jpg)

Unplugged Initial Full Charge:
![Screenshot_20221012_152847_CaptivePortalLogin](https://user-images.githubusercontent.com/19560753/195483281-78e11f7f-a935-4beb-bb1a-e5f7f3558c2c.jpg)

2nd Full Charge:
![Screenshot_20221012_190855_CaptivePortalLogin](https://user-images.githubusercontent.com/19560753/195483169-7fafd93d-c2c4-4e1c-a651-8893bc84b140.jpg)

Unplugged 2nd Full Charge:
![Screenshot_20221012_190919_CaptivePortalLogin](https://user-images.githubusercontent.com/19560753/195483196-3f6172b3-9942-42b8-b9f3-71855a6d238e.jpg)

**Comment by lolwheel** [comment]
Owie has no say in charging, it cannot control anything.

Owie reports the battery percentage based on voltages and in your case the voltages do indeed fall pretty significantly. The BMS ignores the voltages so that's why you don't see the percentage drop without Owie.

You'll get the same mileage out of the battery with or without Owie. The only thing amiss will be percentage reported.

Are you using a quick charger by any chance? Cells dropping from 4.2 to 4.11 is pretty dramatic, I haven't seen anything close to that myself. Higher current charger might explain this.

anyways nothing Owie can fix except implementing Ah-based percentage counting which I don't have much interest in at this point, closing the issue.

**Comment by briderx** [comment]
Right on. Np. To answer your question: I don't use the quick charger. Just the regular one. ❤️❤️❤️
